https: //icons.terrastruct.com/social/041-forrst.svg {
  shape: oval
  style.shadow: false
}
option 1: {
  style.3d: true
  style.shadow: true
  style.multiple: true
  style.double-border: true
  style.opacity: 1
}

Jake -> Some cats: likes
option 1 -> Jake

layers: {
  cats: {
    Siamese
    Persian
    Shorthair
  }
}
